// set
export const CONTAINER_LOAD_START_CREATE = 'CREATE_CONTAINER_LOAD_START'
export const CONTAINER_LOAD_END_CREATE = 'CREATE_CONTAINER_LOAD_END'
export const CONTAINER_SPA_END_CREATE = 'CREATE_CONTAINER_SPA_END'
export const CONTAINER_VIEW_CREATE = 'CREATE_CONTAINER_VIEW'
export const CONTAINER_USER_CREATE = 'CREATE_CONTAINER_USER'

export const MENU_DATA_CREATE = 'SET_MENU_DATA'
